version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps[pip]): update"

  - github-actions:
      ignore:
        - "dependabot.yml"
      directory: "/"
      schedule:
        interval: "weekly"
      commit-message:
        prefix: "chore(deps[github-actions]): update"