version: '3.9'

services:
    app:
        image: mcr.microsoft.com/devcontainers/go:1.22-bullseye
        ports:
            - '8080:8080'
        volumes:
            - ../..:/workspaces:cached
            - '${HOME}/.ssh:/home/vscode/.ssh:ro'

        command: /bin/sh -c "while sleep 1000; do :; done"
