name: Test Installation

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                  pacman -Syu --noconfirm git sudo

            - name: Run Install Script
              run: |
                  chmod +x install.sh
                  ./install.sh

    semantic-release:
        name: Semantic Release
        needs: [test]
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v4
            - name: Run semantic-release
              if: github.repository == 'bartventer/dotfiles' && github.event_name == 'push'
              run: |
                  yarn global add semantic-release@17 @semantic-release/changelog @semantic-release/git
                  semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
