name: Test Installation

on: [push, pull_request]

jobs:
    test-linux:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                image:
                    [
                        'archlinux:latest',
                        'debian:latest',
                        'fedora:latest',
                        'ubuntu:latest',
                    ]
        container:
            image: ${{ matrix.image }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: |
                  # Determine package manager based on image name
                  case "${{ matrix.image }}" in
                      debian:*|ubuntu:*)
                          apt-get update
                          apt-get install -y build-essential git zsh curl procps
                          ;;
                      fedora:*)
                          dnf install -y gcc git zsh curl procps-ng
                          ;;
                      archlinux:*)
                          pacman -Syu --noconfirm base-devel git zsh curl procps-ng
                          ;;
                  esac

            - name: Run Install Script
              run: |
                  chmod +x install.sh
                  zsh ./install.sh

    test-macos:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: |
                  brew install gcc git zsh curl

            - name: Run Install Script
              run: |
                  chmod +x install.sh
                  zsh ./install.sh

    semantic-release:
        name: Semantic Release
        needs: [test-linux, test-macos]
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v4
            - name: Run semantic-release
              if: github.repository == 'bartventer/dotfiles' && github.event_name == 'push'
              run: |
                  yarn global add semantic-release@17 @semantic-release/changelog @semantic-release/git
                  semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
